# https://github.com/nangtani/blender-addon-tester/blob/master/.github/workflows/test-fake-addon-example-from-local-wheel.yml
name: test-addon

on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        blender-version: ["3.2", "3.1", "3.0", "2.93"]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]
    env:
      BLENDER_CACHE: ${{ github.workspace }}/.blender_releases_cache # The place where blender releases are downloaded
      BLENDER_VERSION: ${{ matrix.blender-version }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache Blender release download
        uses: actions/cache@v1
        with:
          path: ${{ env.BLENDER_CACHE }}
          key: ${{ matrix.os }}-blender-${{ matrix.blender-version }}

      - name: Setup Environment
        run: pip install -r testing/requirements.txt

      - name: Test Blender ${{ matrix.blender-version }} x ${{ matrix.os}}
        run: python testing/test_addon.py ActRec ${{ matrix.blender-version }} unit
