name: Update Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  update:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Update to new Version
        id: "update"
        run: |
          output=$(python ./scripts/update_version.py -files $(jq -r '.[]' <<<'${{ steps.files.outputs.all }}'))
          set-output name=log::$output
      - name: Print Log
        run: echo "${{ steps.update.outputs.log }}"
        